// <auto-generated />
using System;
using Librarian.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Librarian.Migrations
{
    [DbContext(typeof(RentalsContext))]
    [Migration("20181023172016_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Librarian.Models.Rental", b =>
                {
                    b.Property<int>("RentalID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("RentalDate");

                    b.Property<DateTime>("ReturnDate");

                    b.HasKey("RentalID");

                    b.ToTable("Rental");

                    b.HasData(
                        new { RentalID = 1, RentalDate = new DateTime(2018, 10, 23, 19, 20, 16, 644, DateTimeKind.Local), ReturnDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local) },
                        new { RentalID = 2, RentalDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local), ReturnDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local) },
                        new { RentalID = 3, RentalDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local), ReturnDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local) },
                        new { RentalID = 4, RentalDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local), ReturnDate = new DateTime(2018, 10, 23, 19, 20, 16, 647, DateTimeKind.Local) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
